import { projects } from './projects.mjs';
const tags = values => values.map(t=>`<span class="tech-chip">${t}</span>`).join('');
const heading = (label,title) => `<div class="section-title"><p>${label}</p><h2>${title}</h2></div>`;
export function redesignHome() {
 const skillGroups=[['⌘','Frontend',['HTML','CSS','JavaScript','TypeScript','React']],['▤','Backend',['Java','Spring Boot','Python','FastAPI','REST APIs']],['☁','Database & Cloud',['PostgreSQL','Oracle','Docker','Cloudflare R2','GitHub Actions']]];
 const capabilities=[['Java Backend Development','I build APIs and business logic with Java and Spring Boot, connecting clear domain models to reliable data workflows.'],['Full-Stack Applications','I connect responsive React interfaces to backend services, from access-change simulations to campus marketplaces.'],['AI-Powered Tools','I integrate language models into useful product workflows, with structured results, explicit assumptions, and fallback paths.'],['Testing & Quality','My experience spans API, database, regression, and accessibility testing, alongside automated integration coverage.'],['Data & Research','I turn Python analysis into reproducible outputs and interactive visualizations that make findings and limitations clear.'],['Cloud Delivery','I work with containerized applications, persistent databases, object storage, and automated delivery workflows.']];
 const cards=projects.map(p=>`<article class="project"><div class="project-artwork">${p.art}</div><div class="project-copy"><h3><a href="/projects/${p.slug}/">${p.name}<span aria-hidden="true"> ↗</span></a></h3><p>${p.summary}</p><a class="case-link" href="/projects/${p.slug}/">Explore case study →</a></div></article>`).join('');
 return `<section class="reference-hero" id="about"><div class="wrap hero-layout"><div class="availability">Available for work <span aria-hidden="true">✣</span></div><div class="hero-copy"><h1>Hello, I'm Sourav Chandhok<br>I'm a <span class="role-text" data-role aria-hidden="true">Java Developer</span><span class="sr-only">Java, full-stack, and AI application developer</span></h1><p>A new Computer Science graduate building thoughtful Java backends, full-stack applications, and AI-powered tools. Seeking full-time opportunities across Canada.</p><div class="social-buttons"><a href="https://github.com/souravC01">↗ GitHub</a><a href="mailto:sourav.chandhok@gmail.com">✉ sourav.chandhok@gmail.com</a><a href="https://www.linkedin.com/in/souravchandhok">in LinkedIn</a><a href="/resume.pdf" download="Sourav-Chandhok-Resume.pdf">↓ Résumé</a></div></div><div class="hero-photo"><img src="/assets/sourav-chandhok.jpeg" width="1086" height="1448" alt="Sourav Chandhok" fetchpriority="high"><div class="photo-badge"><span aria-hidden="true">◎</span><div><strong>4</strong><small>Featured projects</small></div></div></div></div><a class="scroll-down" href="#skills" aria-label="Explore my skills">↓</a></section>
 <section class="section" id="skills"><div class="wrap">${heading('TECHNOLOGIES I WORK WITH','My Skills')}<div class="skill-panels">${skillGroups.map(([icon,name,items])=>`<article class="skill-panel"><h3><span aria-hidden="true">${icon}</span>${name}</h3><p>${name}</p><div class="tech-list">${tags(items)}</div></article>`).join('')}</div></div></section>
 <section class="section" id="services"><div class="wrap">${heading('WHAT I BUILD','Development & engineering')}<div class="capability-grid">${capabilities.map(([title,desc])=>`<article><h3>${title}</h3><p>${desc}</p></article>`).join('')}</div></div></section>
 <section class="section" id="experience"><div class="wrap">${heading('PROFESSIONAL EXPERIENCE','Overview of my career')}<div class="career-list"><article class="career-item"><div class="career-icon" aria-hidden="true">⌘</div><div><h3>Application Programmer Analyst Co-op</h3><p class="organization">ONTARIO MINISTRY OF EDUCATION</p><p class="date">May 2023 – August 2024</p><p>Supported React and Java applications for Ontario government education and financial-assistance services. Investigated REST API and Oracle data flows, implemented application changes, and collaborated with developers, business analysts, and QA teams on release validation.</p><p>Built and executed 500+ manual and automated test cases, identified and tracked 200+ defects, and supported 5+ release cycles, including regression and accessibility testing.</p><div class="tech-list">${tags(['Java','React','Oracle','Selenium','Postman','Jenkins'])}</div></div></article><article class="career-item"><div class="career-icon" aria-hidden="true">◇</div><div><h3>BSc (Honours), Computer Science</h3><p class="organization">YORK UNIVERSITY</p><p class="date">Academic requirements completed · Convocation October 2026</p><p>Computer Science graduate with the Bergeron Entrepreneurs in Science and Technology (BEST) Certificate. My portfolio brings together backend engineering, applied AI, production applications, and network research.</p></div></article></div><div class="resume-row"><a class="button" href="/resume.pdf" download="Sourav-Chandhok-Resume.pdf">Download my résumé ↓</a></div></div></section>
 <section class="section" id="work"><div class="wrap">${heading('SOFTWARE PROJECTS & RESEARCH','My Projects')}<div class="project-grid">${cards}</div></div></section>
 <section class="contact" id="contact"><div class="wrap">${heading('LET’S CONNECT','Have an opportunity in mind?')}<p>I'm available for full-time software engineering opportunities across Canada.</p><div class="social-buttons"><a href="mailto:sourav.chandhok@gmail.com">✉ sourav.chandhok@gmail.com</a><button data-copy-email>Copy email</button><a href="https://www.linkedin.com/in/souravchandhok">in LinkedIn</a></div><p class="copy-status" role="status" data-copy-status></p></div></section>`;
}

