const diagram=(label,nodes,note,extra='')=>`<div class="project-art technical ${extra}"><span class="small">${label}</span><div class="flow">${nodes.map((n,i)=>`${i?'<span aria-hidden="true">→</span>':''}<div class="node ${i===1?'active':''}">${n}</div>`).join('')}</div><div class="flow-label">${note}</div></div>`;
export const projects=[
{slug:'roleimpact',name:'RoleImpact',category:'JAVA / SYSTEM DESIGN',filterCategory:'java-systems',timeline:'Sep – Dec 2024',subtitle:'DETERMINISTIC PERMISSION & GRAPH SIMULATION',watermark:'ROLEIMPACT',themeColor:'#3b82f6',featuredBadge:'★ Core System',summary:'Understand the business consequences of an access change before making it. RoleImpact is a Java 21 and Spring Boot simulation platform that models employees, roles, permissions, and workflows to identify downstream impact and evaluate mitigation options.',tags:['Java 21','Spring Boot','Docker','React','Testcontainers','PostgreSQL','Flyway'],demo:'https://roleimpact.vercel.app/',repo:'https://github.com/souravC01/RoleImpact',focus:'Deterministic simulation & graph modeling',role:'Full-stack portfolio project',format:'Interactive web application',art:diagram('Access-change simulation',['Role removed','Impact analysis','Mitigation'], 'Trace the change. Explain the impact. Test the recovery.')},
{slug:'jobhelperguru',name:'JobHelperGuru',category:'Applied AI / Full-stack',filterCategory:'applied-ai',timeline:'Jul – Dec 2025',subtitle:'AI-ASSISTED RÉSUMÉ & JOB SEARCH WORKSPACE',watermark:'JOBHELPER',themeColor:'#a855f7',featuredBadge:'★ Featured',summary:'A job-search workspace built with Python, FastAPI, and React that analyzes postings, matches résumés, suggests evidence-aware bullets, and features an offline heuristic fallback.',tags:['Python','FastAPI','React','OpenAI API','pytest','PostgreSQL'],demo:'https://jobhelperguru.onrender.com/',repo:'https://github.com/souravC01/JobHelperGuru',focus:'AI integration & application workflows',role:'Full-stack portfolio project',format:'Interactive web application',art:diagram('Job application workflow',['Job posting','Résumé fit','Application tracker'],'Structured analysis with cloud, local, and heuristic paths.','job-art')},
{slug:'yu-bazaar',name:'YU Bazaar',category:'JAVA / CLOUD & SECURITY',filterCategory:'java-systems',timeline:'2024 – 2025',subtitle:'SECURE CAMPUS MARKETPLACE',watermark:'YU BAZAAR',themeColor:'#10b981',featuredBadge:'★ Campus MVP',summary:'A modernized Java campus marketplace for York University students featuring Spring Security, OTP verification, RabbitMQ asynchronous messaging, and Kubernetes containerization.',tags:['Java 17','Spring Security','PostgreSQL','Kubernetes'],demo:'https://yu-bazaar.onrender.com/',repo:'https://github.com/souravC01/yu-bazaar',focus:'Authentication, persistence & deployment',role:'Team contributor & independent modernization',format:'Campus marketplace',art:diagram('Campus marketplace',['Verify account','Discover listings','Contact seller'],'Spring Boot · persistent data · cloud image storage')},
{slug:'toronto-airbnb',name:'Toronto Airbnb Market Network',category:'DATA ANALYTICS / NETWORK SCIENCE',filterCategory:'research',timeline:'Nov 2025',subtitle:'15,809 LISTINGS NETWORK COMMUNITY ANALYSIS',watermark:'AIRBNB NET',themeColor:'#ff5c39',featuredBadge:'★ Research',summary:'Do rental markets follow neighbourhood boundaries? An interactive network analysis and research case study of 15,809 Toronto Airbnb listings with Louvain/Leiden community detection.',tags:['Python','React','TypeScript','Network Science','Data Analysis'],demo:'https://toronto-airbnb-market-network.vercel.app/',repo:'https://github.com/souravC01/toronto-airbnb-market-network',focus:'Network science & reproducible analysis',role:'Portfolio edition & interactive presentation',format:'Research & interactive data exploration',art:diagram('Market network analysis',['15,809 listings','Communities','Validation'],'Geography + shared hosts + listing similarity.')}
];

projects[0].repo='https://github.com/souravC01/RoleImpact';
projects[1].repo='https://github.com/souravC01/JobHelperGuru';
projects[2].art='<div class="project-art"><a href="/assets/yu-bazaar.jpg" aria-label="View full YU Bazaar marketplace screenshot"><img src="/assets/yu-bazaar.jpg" alt="YU Bazaar marketplace with four listings and Public Seller and York Verified badges" width="1890" height="816" loading="lazy"></a></div>';
projects[3].art='<div class="project-art"><a href="/assets/airbnb-network.png" aria-label="View full Toronto Airbnb community map"><img src="/assets/airbnb-network.png" alt="Map of Toronto Airbnb listings colored by Graph C Louvain market community" width="2250" height="2100" loading="lazy"></a></div>';
const section=(id,title,html)=>({id,title,html});
projects[0].sections=[
section('problem','The problem','<p>Removing access is easy to describe as a permissions change. The harder question is what the organization can no longer do afterward. A role might be the only thing keeping a time-sensitive business workflow covered.</p><p>RoleImpact models employees, roles, permissions, capabilities, and workflow requirements together so an access change can be evaluated in terms of its operational consequences.</p>'),
section('role','What I built','<p>I designed and built the React and TypeScript interface, Spring Boot REST API, object-oriented Java impact-analysis engine, and PostgreSQL persistence layer. The application connects an interactive organization model to deterministic backend simulations so users can trace why a workflow is affected and compare possible mitigations.</p>'),
section('approach','From change to consequence','<p>A user opens an organization model, removes a role, and runs an impact simulation. RoleImpact traces the affected relationship paths from employee access through permissions and capabilities to business workflows.</p><p>The user can then evaluate a replacement, compare the original and mitigated results, and inspect the evidence behind each recommendation. Because the engine is deterministic, identical organization states and changes produce identical results.</p>'),
section('architecture','Architecture','<ul><li><strong>React + TypeScript:</strong> interactive organization modeling, impact visualization, relationship paths, and before-and-after comparisons.</li><li><strong>Java 21 + Spring Boot:</strong> REST API and application services for organization models, impact simulations, mitigation scenarios, and saved drafts.</li><li><strong>Deterministic Java impact engine:</strong> evaluates access changes against immutable organization snapshots, traces affected workflows, produces stable result hashes, and ranks eligible mitigation options.</li><li><strong>PostgreSQL + Spring Data JPA + Flyway:</strong> stores organization data and simulation relationships while maintaining versioned database migrations.</li><li><strong>JUnit + Testcontainers:</strong> validates application and persistence behaviour against real PostgreSQL container instances rather than relying only on mocked database tests.</li><li><strong>Docker:</strong> provides a reproducible local PostgreSQL environment and consistent development setup.</li></ul>'),
section('challenges','Engineering challenges','<p>A replacement recommendation cannot simply match a role name. It must satisfy the permissions and capabilities required by the affected workflows while actually restoring coverage. That required recommendation logic to operate on the same domain model used by the impact engine rather than relying on superficial similarity.</p><p>Another challenge was making simulation results reproducible. Organization state is assembled into immutable snapshots, allowing the engine to compare original and alternative scenarios without mutating the underlying model. Stable result hashing also makes equivalent simulations identifiable.</p><p>The interface also needed to explain relationship-rich results without making a graph the only way to understand them. RoleImpact therefore exposes textual relationship paths and rule-based evidence alongside the visual representation.</p>'),
section('results','Result and scope','<p>RoleImpact demonstrates an end-to-end workflow from an access change to an evidence-backed impact explanation and tested mitigation. Simulations can be persisted and compared while organization data remains available across sessions.</p><p>The application is a portfolio simulation using synthetic organization data. It does not connect to production identity providers or modify real permissions, and it is not intended for confidential organizational data.</p>'),
section('learning','What the project taught me','<p>The biggest design lesson was that explainability has to exist in the domain model and engine but not be added only in the interface. A useful result needs to preserve the relationship path and rule that produced it so the frontend can explain why a workflow was affected and why a mitigation is valid. The project also reinforced the value of deterministic state, explicit domain models, database-backed integration testing, and designing APIs around business behaviour rather than UI screens.</p>')];
projects[1].sections=[
section('problem','The problem','<p>Job applications involve repeated context switching: reading a posting, comparing it with several résumés, tailoring the wording, and remembering what was submitted. JobHelperGuru brings those steps into a shared workspace.</p>'),
section('role','My contribution','<p>I built the React and Python/FastAPI application, provider-independent LLM integration, résumé-matching workflow, and supporting authentication, document storage, and application tracking architecture.</p>'),
section('approach','A connected application workflow','<p>Users paste a job description or submit a posting URL, inspect the extracted qualifications, compare stored résumés, and revise individual bullets before tracking the application.</p><p>Cloud and local models use an OpenAI-compatible interface. An offline heuristic fallback supports pasted-job analysis and keyword matching even without an external model key.</p>'),
section('architecture','Architecture','<ul><li><strong>React:</strong> job analysis, résumé inspection, settings, and table or Kanban application tracking.</li><li><strong>FastAPI:</strong> application endpoints, authenticated workflows, and structured Pydantic response models.</li><li><strong>AI engine & Offline fallback:</strong> structured job analysis, résumé ranking, and claim-aware bullet suggestions, with an offline heuristic fallback to preserve core functionality.</li><li><strong>PostgreSQL and Cloudflare R2:</strong> application records and résumé document storage, with local development alternatives.</li><li><strong>pytest Automated Testing:</strong> comprehensive test suite verifying API routes, authentication, data processing, and application logic.</li><li><strong>openpyxl:</strong> automated spreadsheet exports and application tracking workflows.</li></ul>'),
section('challenges','Useful suggestions, grounded claims','<p>The most important constraint is avoiding résumé suggestions that silently invent experience. Bullet suggestions distinguish supported claims from unverified skills and metric placeholders. The user remains responsible for reviewing every suggested statement.</p><p>Model responses and scraped job pages are variable inputs. Parsing and fallback paths keep the workflow usable when a provider response cannot be interpreted or no model is configured.</p>'),
section('results','Result and scope','<p>The project combines job analysis, multi-résumé matching, bullet revision, application tracking, and Excel export in one application. It demonstrates applied AI integrated with ordinary product workflows and persistent user data.</p><p>Résumé match percentages are application heuristics, not validated hiring predictions or guarantees of compatibility with an employer’s ATS. AI suggestions require review, and URL ingestion depends on source-site accessibility.</p>'),
section('learning','What the project taught me','<p>AI features need explicit contracts, failure paths, and clear distinctions between evidence and suggestions. The fallback experience is part of the product, and generated text is most useful when its assumptions are visible.</p>')];
projects[2].sections=[
section('problem','The problem','<p>A campus marketplace needs more than listings. People need to understand who is selling, recover access to their accounts, upload photographs, and contact sellers without exposing internal credentials or giving other users control over their listings.</p>'),
section('role','Team origins, individual contribution','<p>The original application was a four-person York University course project. My original contributions included registration and recovery email notifications, password recovery, York email OTP verification, item search and live suggestions, and listing/homepage workflow fixes.</p><p>I then maintained an independent portfolio edition, adding production infrastructure, security improvements, cloud media storage, verification tiers, a protected demo, automated tests, and deployment work. The <a href="https://github.com/hvpham-yorku/YuBazaar">original team repository</a> and contributor credit remain distinct from these later improvements.</p>'),
section('approach','A complete marketplace journey','<p>Visitors can browse public listings. Sellers register and verify an email address; York email verification adds a York Verified Student badge. Listing ownership determines who can change or delete an item.</p><p>Reviewers can choose the read-only demo from the sign-in screen. Buyers use controlled email inquiries to contact sellers; payments and exchanges happen outside the application.</p>'),
section('architecture','Architecture','<ul><li><strong>Java 17 + Spring Boot + Thymeleaf:</strong> service for server-rendered pages and application workflows.</li><li><strong>Spring Security:</strong> sessions, route protection, BCrypt password hashing, OTP verification, ownership policies, and demo restrictions.</li><li><strong>RabbitMQ:</strong> asynchronous message queue for email verification, password resets, and user notifications.</li><li><strong>Kubernetes & Docker:</strong> containerized deployment orchestrating marketplace services with high reliability.</li><li><strong>PostgreSQL + Flyway:</strong> persistent accounts/listings and versioned database migrations.</li><li><strong>Cloudflare R2 & AWS SDK:</strong> photograph storage with delivery through application-controlled routes.</li><li><strong>GitHub Actions CI/CD:</strong> automated Maven build and test suite running on every commit.</li></ul>'),
section('challenges','Making the course project durable','<p>Moving beyond local development meant addressing data and image persistence, expiring verification and recovery credentials, owner-only mutations, and safe reviewer access.</p><p>The verification model also needed precise language: a Public Seller is not necessarily a York student, while the York badge indicates verified institutional email ownership.</p>'),
section('results','Result and scope','<p>The portfolio edition is a deployed marketplace with public browsing, persistent listings and photographs, account recovery, verification tiers, and a read-only reviewer path. The repository includes automated coverage of authentication, ownership, recovery, and media behavior.</p><p>This is a portfolio MVP. Payments, escrow, delivery, and real-time chat are outside its scope. The hosted application may take time to wake after inactivity.</p>'),
section('learning','What the project taught me','<p>Production readiness often lives in the less visible paths: recovery, retries, persistence, ownership, and test coverage. Improving an existing team project also requires clear attribution and careful preservation of its original work.</p>')];
projects[3].sections=[
section('problem','The research question','<p>Do Toronto’s Airbnb market segments follow official neighbourhood boundaries? Geographic proximity is only one relationship: listings can also share hosts or similar characteristics.</p><p>The analysis models 15,809 listings from a November 2025 Toronto snapshot as a weighted network and asks whether detected communities add useful information to price prediction.</p>'),
section('role','My portfolio contribution','<p>I built the responsive React and TypeScript presentation, a reproducible Python pipeline for application data, and automated checks that keep displayed metrics synchronized with canonical analysis outputs.</p><p>This is an independently maintained portfolio edition of a York University EECS 4414 research project. The original final report retains its original submission authorship; this page does not claim sole authorship of that course report.</p>'),
section('approach','Build the network in layers','<ul><li><strong>Graph A:</strong> geographic proximity within 500 metres.</li><li><strong>Graph B:</strong> adds shared-host ownership.</li><li><strong>Graph C:</strong> adds listing-attribute similarity.</li></ul><p>Louvain and Leiden community detection are compared against official neighbourhoods. Price is excluded from edge construction. A paired ridge-regression comparison then tests whether community membership adds information beyond the baseline price model.</p>'),
section('architecture','From analysis to interactive evidence','<p>Python experiments produce canonical tables and figures. A validation step checks those outputs, and the React presentation exposes graph layers, community algorithms, validation schemes, and sensitivity results.</p><p>The presentation is exported as static HTML, with browser-side interactivity. GitHub Actions checks the application and analytical artifacts so changes to the research do not silently leave the website out of sync.</p>'),
section('challenges','Testing the interpretation','<p>Communities depend on modeling choices. The project uses seven parameter configurations and random, host-grouped, and spatial-block five-fold validation to examine how stable the results are.</p><p>Separating exploratory segmentation from predictive usefulness is essential: a visually interesting map does not establish that its labels improve a predictive model.</p>'),
section('results','Findings and limitations','<p>Adding ownership and similarity links connects geographic clusters into broader market segments. Spatial-only communities align most closely with official neighbourhoods, while the full graph spans those administrative boundaries.</p><p>Community membership increases mean raw R² by only 0.0016–0.0024 across validation schemes; adjusted R² declines. The study therefore does not claim a material price-prediction improvement.</p><p>Validation is transductive: communities are learned from the full price-free graph before price folds are created. It is not a deployment test on completely unseen listings. The dataset is one time snapshot, and exact community membership changes with parameters.</p>'),
section('learning','What the project taught me','<p>A strong research presentation makes its uncertainty inspectable. Reproducible artifacts, explicit validation assumptions, and honest reporting make the findings more useful than a claim of improvement unsupported by the results.</p><p><a href="https://toronto-airbnb-market-network.vercel.app/report/EECS4414-Airbnb-Network-Analysis-Final-Report.pdf">Read the original course report ↗</a> · <a href="https://github.com/souravC01/toronto-airbnb-market-network/blob/main/docs/ROBUSTNESS.md">Read the robustness methodology ↗</a></p>')];
